version: '3.8'
services:
  frontend:
    build: ./openmeter-frontend
    ports:
      - "3000:3000"
    container_name: openmeter-frontend
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    container_name: openmeter-backend
    restart: always
    

  